// ============================================================
// MONETA — PLANS DE RÉFÉRENCE (validés par JFD le 08/10/2026)
// Recoupés sur les actes SIGNÉS : AKZO NOBEL / ADHEFIN (01/09/2026)
// et R3S / CAUVAS (28/09/2026). Chaque plan suit les articles de l'acte,
// dans leur ordre ; une rubrique = une question (grain le plus fin,
// on fusionne à l'usage, jamais l'inverse).
// Une rubrique précédée de « (o) » est OPTIONNELLE : tirée d'un autre
// acte (CID, NewCold, Domengies), absente de l'acte de référence.
// IMPORTANT : ce fichier sert seulement à CRÉER le clausier d'un type
// d'acte la première fois. Ensuite, le clausier enregistré sur le Drive
// fait foi (numéros permanents) : modifier ce fichier ne change rien
// à un clausier déjà créé, SAUF les articles listés dans « ajouts »,
// ajoutés une fois en fin de plan (09/10/2026 : « Clôture et signature »).
// ============================================================
window.PLANS = {
  "promesse-synallagmatique": {
    prefixe: "PSV",
    reference: "AKZO NOBEL / ADHEFIN INTERNATIONAL, 01/09/2026",
    articles: [
      ["Définitions – interprétation", ["Définitions", "Interprétation"]],
      ["Identification des parties", ["Identification du vendeur", "Identification de l'acquéreur"]],
      ["Présence – représentation", ["Représentation du vendeur", "Représentation de l'acquéreur"]],
      ["Déclarations sur la capacité", ["Capacité du vendeur", "Capacité de l'acquéreur"]],
      ["Pièces relatives à la capacité", ["Pièces relatives à la capacité"]],
      ["Quotités acquises", ["Quotités acquises"]],
      ["Exposé – intention des parties", ["Rappel des textes", "Dossier d'information : constitution et transmission", "Déclarations du vendeur sur le dossier d'information", "Actualisation du dossier d'information", "Déclarations de l'acquéreur sur l'étude du bien", "Devoir d'information réciproque", "Non-application de l'article L. 271-1", "Imprévision", "Envoi du projet d'acte", "Projet de l'acquéreur", "Articulation avec le contrat de cession d'activité"]],
      ["Objet – promesse synallagmatique", ["Engagements réciproques de vendre et d'acquérir", "Report du transfert de propriété", "Nature et quotités des droits", "Nature juridique et irrévocabilité", "Interdiction de disposer", "Inefficacité de la rétractation unilatérale"]],
      ["Faculté de substitution", ["Bénéficiaires de la substitution et solidarité", "Substitution et article L. 271-1", "Substitution sur la totalité du bien", "Information et forme de la substitution", "Sort des sommes versées", "Effets de la substitution", "Interdiction de cession entre professionnels"]],
      ["Identification du bien", ["Désignation", "Historique cadastral", "Lotissement", "Attestation d'exactitude de la désignation", "Plan cadastral", "Plan Géoportail", "Plans et superficie", "Remise du relevé des surfaces", "Contenance et limites cadastrales", "Usage du bien", "Accès au bien"]],
      ["Absence de meubles", ["Absence de meubles"]],
      ["Effet relatif", ["Effet relatif"]],
      ["Origine de propriété", ["Origine de propriété immédiate", "Origine de propriété antérieure", "Origine de propriété plus antérieure"]],
      ["Situation hypothécaire", ["Situation hypothécaire"]],
      ["Situation locative", ["Situation locative"]],
      ["Constatation de la vente", ["Durée de la promesse", "Date de la vente calée sur le contrat de cession", "Information sur la réalisation des conditions", "Renonciation aux conditions", "Non-rétroactivité et condition réputée accomplie", "Caducité à défaut de réalisation", "Administration du bien jusqu'à la vente", "Consignation du prix et des frais", "Perfection de la vente et transfert des risques", "Obligation de réitérer et notaire rédacteur", "Mise en demeure de signer", "Computation des délais", "Procès-verbal de carence et choix de la partie diligente"]],
      ["Prix – conditions financières", ["Prix", "Paiement du prix", "Frais", "Commission des intermédiaires", "Dépôt de garantie"]],
      ["Déclarations fiscales", ["Régime fiscal de la promesse", "Plus-value", "Qualité d'assujettis à la TVA", "Transmission d'universalité (article 257 bis)", "Régularisations de TVA", "Droit d'enregistrement"]],
      ["Condition particulière", ["Ensemble indissociable", "Caducité à défaut de cession concomitante"]],
      ["Conditions suspensives", ["Principe et textes", "Condition à laquelle aucune partie ne peut renoncer", "Droits de préemption", "Conditions auxquelles seul l'acquéreur peut renoncer", "Urbanisme", "Situation hypothécaire", "Servitudes", "Origine de propriété", "Absence de condition de financement", "Notification de la réalisation des conditions"]],
      ["Charges et conditions générales", ["Garantie d'éviction", "Subrogation dans les droits et actions", "Garantie de jouissance", "Garantie hypothécaire", "État du bien", "Contenance de l'assiette foncière", "Contenance des constructions", "Servitudes", "Taxe foncière des années antérieures", "Prorata de taxe foncière", "Assurances", "Contrat d'affichage", "Antennes téléphoniques", "Panneaux photovoltaïques", "Procédures et litiges", "Contentieux", "Contrats de distribution et de fourniture", "Contrats de gestion, de maintenance et d'entretien", "Contrats de travail"]],
      ["Réglementations particulières", ["Renseignement d'urbanisme et plan local d'urbanisme", "Monument historique", "Absence de changement de destination", "Absence de construction ou de rénovation depuis dix ans", "Travaux réalisés déclarés", "Autorisations administratives", "Dossier d'intervention ultérieure sur l'ouvrage", "Dossier de diagnostics : rappel des textes", "Contenu du dossier de diagnostics", "Amiante", "Termites", "Mérules", "Performance énergétique", "État des risques", "Sinistres indemnisés", "Assainissement", "Eaux usées non domestiques", "Contrôle du raccordement et travaux correctifs"]],
      ["Situation environnementale", ["Rappel des textes", "Investigations sur les installations classées", "Terres excavées", "Bases de données consultées", "Diagnostics environnementaux", "Déclarations du vendeur", "Installations classées exploitées", "Convention des parties sur l'environnement", "Déchets", "Sols et sous-sol", "Légionellose", "Fluides frigorigènes", "Pyralène"]],
      ["Dispositions diverses", ["Reprise par les ayants droit du vendeur", "Survie de l'acquéreur", "Nouveaux états et diagnostics", "Contradiction", "Clause de sauvegarde"]],
      ["Gestion pendant la période de transfert", ["Engagements de ne pas faire", "Engagements généraux", "Travaux imposés par une nouvelle réglementation", "Travaux urgents", "Garde du bien", "Immeubles par destination", "Visite préalable"]],
      ["Sinistre total ou partiel", ["Sinistre total", "Sinistre significatif", "Sinistre partiel"]],
      ["Notifications", ["Notifications"]],
      ["Confidentialité", ["Principe", "Exceptions", "Annonces"]],
      ["Provision sur les frais de la vente", ["Provision sur frais"]],
      ["Paiement sur état – publicité foncière", ["Enregistrement au droit fixe", "Publicité foncière facultative", "Report du transfert de propriété"]],
      ["Pouvoirs", ["Pouvoirs"]],
      ["Élection de domicile", ["Élection de domicile", "Attribution de juridiction"]],
      ["Communication des pièces", ["Communication des pièces"]],
      ["Affirmation de sincérité", ["Affirmation de sincérité"]],
      ["Données personnelles", ["Données personnelles"]],
      ["Certification d'identité", ["Certification d'identité"]],
      ["Formalisme des annexes", ["Formalisme des annexes"]],
      ["Clôture et signature", ["Mention de lecture et d'approbation", "Partie ne comprenant pas le français", "Signature électronique ou à distance", "Signature des parties", "Signature du notaire, date et lieu"]],
    ],
    // Articles ajoutés après la création du clausier : MONETA les ajoute en fin de plan, une seule fois,
    // à un clausier déjà enregistré qui ne les a pas encore (numéros nouveaux, rien d'existant ne bouge).
    ajouts: ["Clôture et signature"],   // 09/10/2026 — partie finale versée au clausier (JFD)
  },
  "promesse-unilaterale": {
    prefixe: "PUV",
    reference: "R3S / CAUVAS, 28/09/2026",
    articles: [
      ["Définitions – interprétation", ["Définitions", "Interprétation"]],
      ["Identification des parties", ["Identification du promettant", "Identification du bénéficiaire", "(o) Quotités acquises"]],
      ["Présence – représentation", ["Représentation du promettant", "Représentation du bénéficiaire"]],
      ["Déclarations sur la capacité", ["Capacité du promettant", "Capacité du bénéficiaire"]],
      ["Pièces relatives à la capacité", ["Pièces relatives à la capacité"]],
      ["Exposé – intention des parties", ["Rappel des textes", "Non-application de l'article L. 271-1", "Imprévision", "Envoi du projet d'acte", "(o) Dossier d'information", "(o) Contexte de l'opération", "(o) Projet du bénéficiaire", "(o) Devoir d'information réciproque"]],
      ["Objet du contrat", ["Objet du contrat", "Nature et quotités des droits"]],
      ["Faculté de substitution", ["Principe et solidarité du bénéficiaire initial", "Substitution et délai de rétractation", "Information et forme de la substitution", "Sort des sommes versées", "Effets de la substitution", "Interdiction de cession entre professionnels"]],
      ["Identification du bien", ["Désignation", "Lotissement", "Historique cadastral", "Division", "Attestation d'exactitude de la désignation", "Plan cadastral", "Plan Géoportail", "Usage du bien", "Accès au bien", "(o) Délimitation du terrain", "(o) Bornage"]],
      ["Meubles", ["Absence de meubles", "Mobilier compris sans valorisation", "(o) Meubles vendus et ventilation du prix"]],
      ["Effet relatif", ["Effet relatif"]],
      ["Origine de propriété", ["Origine de propriété"]],
      ["Situation hypothécaire", ["Situation hypothécaire"]],
      ["Situation locative", ["Situation locative et occupation", "(o) Logement décent"]],
      ["Constatation de la vente", ["Durée de la promesse", "Réalisation par signature de l'acte", "Levée d'option", "Paiement par virement et origine des fonds", "Définition de la carence", "Déchéance faute de levée d'option", "Mise en demeure et procès-verbal après levée d'option", "Défaut du promettant", "Défaut du bénéficiaire", "Force exécutoire et interdiction de disposer", "Exécution en nature", "(o) Prorogation conventionnelle", "(o) Prorogation automatique", "(o) Événement sanitaire", "(o) Information sur le rendez-vous de signature"]],
      ["Propriété – jouissance", ["Propriété", "Jouissance et libération des lieux", "Absence de congé ouvrant un droit de préemption"]],
      ["Prix – conditions financières", ["Prix", "Paiement du prix", "Frais", "Commission des intermédiaires", "(o) Plan de financement", "(o) Consignation des fonds"]],
      ["Indemnité d'immobilisation", ["Montant", "Versement et délai", "Défaut de versement", "Nantissement", "Séquestre", "Sort de la somme", "Libération des fonds et différends", "(o) Absence d'indemnité"]],
      ["Réserves et conditions suspensives", ["Principe et textes", "Condition à laquelle aucune partie ne peut renoncer", "Conditions auxquelles seul le bénéficiaire peut renoncer", "Droits de préemption", "(o) Droit de priorité", "(o) Pacte de préférence", "Urbanisme", "Situation hypothécaire", "Servitudes", "Origine de propriété", "Obtention de prêts", "Notification et mise en demeure sur le prêt", "Renonciation à la condition de prêt", "Justification d'un refus de prêt", "Certificat de conformité technique d'un équipement", "(o) Permis de construire"]],
      ["Conditions et déclarations générales", ["Garantie d'éviction", "Subrogation dans les droits et actions", "Garantie de jouissance", "Garantie hypothécaire", "Servitudes", "État du bien", "Contenance du terrain et des constructions", "Mesurage des surfaces", "Taxe foncière des années antérieures", "Prorata de taxe foncière", "Taxe pour la création de bureaux en Île-de-France", "Taxe annuelle sur les bureaux", "Assurances", "Contrat d'affichage", "Antennes téléphoniques", "Panneaux photovoltaïques", "Procédures et litiges", "Contentieux", "Contrats de distribution et de fourniture", "Contrats de gestion, de maintenance et d'entretien", "Contrats de travail", "(o) Archéologie préventive", "(o) Avantage fiscal lié à une location"]],
      ["Réglementations particulières", ["Dispositions d'urbanisme", "Lotissement", "Caducité des règles d'urbanisme du lotissement", "Cahier des charges du lotissement", "(o) Zone de bruit des aérodromes"]],
      ["Construction", ["Absence de construction ou de rénovation depuis dix ans", "Permis de construire", "Permis modificatifs", "Ouverture de chantier et achèvement", "Conformité des travaux", "Permis non mis en œuvre", "Délai de recours contre le permis", "(o) Travaux de plus de dix ans"]],
      ["Diagnostics", ["Dossier de diagnostics techniques", "Plomb", "Amiante", "Termites", "Mérules", "Performance énergétique", "Radon", "(o) Détecteur de fumée", "(o) Chaudière", "(o) Absence de dossier par accord des parties"]],
      ["Diagnostics environnementaux", ["Assainissement", "Eaux usées non domestiques", "État des risques", "Sinistres indemnisés"]],
      ["Équipements du bien", ["Cuve à fioul", "Citerne de gaz", "Récupération des eaux de pluie", "Puits et forages domestiques", "Forage non domestique"]],
      ["Situation environnementale", ["Rappel des textes", "Investigations sur les installations classées", "Terres excavées", "Bases de données consultées", "Diagnostics environnementaux", "Déclarations du promettant", "(o) Déclarations du bénéficiaire", "(o) Acquisition en l'état", "Déchets", "Sols et sous-sol", "Légionellose", "Fluides frigorigènes", "Pyralène"]],
      ["Fiscalité", ["TVA", "Droits d'enregistrement", "Primo-accédants", "Plus-values"]],
      ["Dispositions diverses", ["Reprise par les ayants droit du promettant", "Survie du bénéficiaire", "Nouveaux états et diagnostics", "Contradiction", "Clause de sauvegarde", "(o) Concours"]],
      ["Gestion pendant la période de transfert", ["Engagements de ne pas faire", "Engagements généraux", "Travaux imposés par une nouvelle réglementation", "Travaux urgents", "Garde du bien", "Immeubles par destination", "Visite préalable", "(o) Engagements du bénéficiaire"]],
      ["Sinistre total ou partiel", ["Sinistre total", "Sinistre significatif", "Sinistre partiel"]],
      ["Notifications", ["Notifications"]],
      ["Confidentialité", ["Principe", "Exceptions", "Annonces"]],
      ["Paiement sur état – publicité foncière", ["Enregistrement au droit fixe", "Publicité foncière facultative", "Report du transfert de propriété", "(o) Provision sur frais", "(o) Rémunération de préparation et de rédaction"]],
      ["Pouvoirs", ["Pouvoirs"]],
      ["Élection de domicile", ["Élection de domicile", "Attribution de juridiction"]],
      ["Communication des pièces", ["Communication des pièces"]],
      ["Affirmation de sincérité", ["Affirmation de sincérité"]],
      ["Données personnelles", ["Données personnelles"]],
      ["Certification d'identité", ["Certification d'identité"]],
      ["Formalisme des annexes", ["Formalisme des annexes"]],
      ["Clôture et signature", ["Mention de lecture et d'approbation", "Partie ne comprenant pas le français", "Signature électronique ou à distance", "Signature des parties", "Signature du notaire, date et lieu"]],
    ],
    // Articles ajoutés après la création du clausier : MONETA les ajoute en fin de plan, une seule fois,
    // à un clausier déjà enregistré qui ne les a pas encore (numéros nouveaux, rien d'existant ne bouge).
    ajouts: ["Clôture et signature"],   // 09/10/2026 — partie finale versée au clausier (JFD)
  },
};
